FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0.100-alpine3.18 AS builder

ARG TARGETARCH

WORKDIR BUILD

COPY ./NuGet.config .
COPY ./src/MeetupMembersApi/MeetupMembersApi.csproj .

RUN dotnet restore -a $TARGETARCH

COPY ./src/MeetupMembersApi .

RUN dotnet publish --no-restore -a $TARGETARCH MeetupMembersApi.csproj -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0.0-alpine3.18
WORKDIR /app

COPY --from=builder /app .

CMD ["dotnet", "MeetupMembersApi.dll"]