FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100-alpine3.9 AS builder
COPY . .

RUN dotnet publish -c Release ./src/FrontEnd/FrontEnd.csproj -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0.0-alpine3.9

USER nobody
WORKDIR /app

COPY --chown=nobody:nobody --from=builder /app .

CMD ["dotnet", "FrontEnd.dll"]