FROM mcr.microsoft.com/dotnet/core/sdk:3.1.100-alpine3.10 AS builder
COPY . .

RUN dotnet test -c Release 
RUN dotnet publish -c Release ./src/MeetupMembersApi/MeetupMembersApi.csproj -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.0-alpine3.10

USER nobody
WORKDIR /app

COPY --chown=nobody:nobody --from=builder /app .

CMD ["dotnet", "MeetupMembersApi.dll"]