version: "3"
services:
  test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2.401-alpine3.9
    depends_on:
      - members.api
      - members.database
    environment:
      - MONGOURL=mongodb://members.database:27017
      - SERVICEURI=http://members.api:9010
    entrypoint: ["dotnet", "test", "./build/test/MeetupMembersApi.Tests/MeetupMembersApi.Tests.csproj", "--configuration", "Release"]
    volumes:
      - .:/build
  frontend:
    container_name: gui
    build:
      context: .
      dockerfile: Dockerfile_FrontEnd
    depends_on:
      - members.api
    environment:
      - MEMBERSAPI__URI=http://members.api:9010
    ports:
      - 80:8080
  members.api:
    build:
      context: .
      dockerfile: Dockerfile_Api_Local
    depends_on:
      - members.database
    environment:
      - MONGO__MONGOCONNECTION=mongodb://members.database:27017
    ports:
      - 9010:9010
  members.database:
    image: mongo:4.0.11
    ports:
      - 27017:27017