version: "3"
services:
  test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2.300-alpine3.9
    depends_on:
      - members.api
      - mongo
    environment:
      - MONGOURL=mongodb://mongo:27017
      - SERVICEURI=http://members.api:9010
    entrypoint: ["dotnet", "test", "./build/test/MeetupMembersApi.Tests/MeetupMembersApi.Tests.csproj", "--configuration", "Release"]
    volumes:
      - .:/build
  frontend:
    container_name: gui
    build:
      context: .
      dockerfile: Dockerfile_FrontEnd
    depends_on:
      - members.api
    environment:
      - MEMBERSAPI__URI=http://members.api:9010
    ports:
      - 80:8080
  members.api:
    container_name: membersapi
    build:
      context: .
      dockerfile: Dockerfile_local
    depends_on:
      - mongo
    environment:
      - MONGO__MONGOCONNECTION=mongodb://mongo:27017
    ports:
      - 9010:9010
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017