FROM mcr.microsoft.com/dotnet/core/sdk:2.2.301-alpine3.9 AS builder
COPY . .

RUN dotnet test -c Release 
RUN dotnet publish -c Release ./src/MeetupMembersApi/MeetupMembersApi.csproj -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2.6-alpine3.9

USER nobody
WORKDIR /app

COPY --chown=nobody:nobody --from=builder /app .

CMD ["dotnet", "MeetupMembersApi.dll"]